### ISSUE TITLE
Option for also showing original size

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/gzip-size-cli#3]
```shell
$> gzip-size file.js --original
20 kB, 2 kB gzipped
```
```shell
$> gzip-size file.js --incl-org
20 kB / 2 kB
```

Google ranks on both metrics, so it is indeed useful information.

**Comment by sindresorhus** [comment]
We could add a `--verbose` flag that shows both:

```
$ gzip-size file.js --verbose
Original:  20 kB
Gzipped:   2 kB
```

Alternatively:

```
$ gzip-size file.js --include-original
20 kB → 2 kB
```

**Comment by stevenvachon** [comment]
I like the arrow in your `--include-original` example, but I think that I like the `--verbose` option name better.

**Comment by sindresorhus** [comment]
Ok, let's go with that then. I think the arrow should be `chalk.dim()`'d.
